AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6
Metrics/ClassLength:
  Max: 150
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false