AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6
Metrics/ClassLength:
  Max: 150
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  Max: 40
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 35
Style/Documentation:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false